"""Collect every [verify: ...] item and TO CONFIRM reminder from specs/*.json into VERIFY.md.

usage: python3 lib/verify_ledger.py   (run from slides/)
"""
import glob, json, os, re

rows = []
for path in sorted(glob.glob("specs/s*.json")):
    spec = json.load(open(path))
    sid = os.path.basename(path).split("-")[0]
    deck = spec["title"]
    for i, sl in enumerate(spec["slides"]):
        title = sl.get("title") or sl.get("type")
        where = ("Backup: " if sl.get("backup") else "") + title
        text = json.dumps({k: v for k, v in sl.items() if k not in ("notes", "answerNotes")}, ensure_ascii=False)
        tags = sorted(set(m.strip() for m in re.findall(r"\[verify:?\s*([^\]]*)\]", text)))
        rem = []
        for n in ("notes", "answerNotes"):
            for r in (sl.get(n) or {}).get("reminders", []):
                if "CONFIRM" in r.upper():
                    rem.append(re.sub(r"^\s*TO CONFIRM BEFORE PRESENTING:?\s*", "", r, flags=re.I).strip())
        if tags or rem:
            rows.append((sid, deck, where, "; ".join(tags) or "—", " / ".join(rem) or "—"))

esc = lambda s: s.replace("|", "\\|").replace("\n", " ")
out = ["# Items to confirm before presenting", "",
       "Generated by `lib/verify_ledger.py` from the specs. Everything else on the slides comes from the",
       "EBMT Handbook 8th ed. chapter text. Items are bracketed `[verify: …]` on the slide and/or listed in",
       "that slide's speaker reminders as TO CONFIRM BEFORE PRESENTING. Book misprints and internal",
       "inconsistencies that were resolved on the slide are noted in each slide's reminders, not here.", "",
       f"**{len(rows)} slides with items to check.**", "",
       "| Session | Deck | Slide | On the slide | What to check |", "|---|---|---|---|---|"]
for sid, deck, where, tags, rem in rows:
    out.append(f"| {sid[1:]} | {esc(deck)} | {esc(where)} | {esc(tags)} | {esc(rem)} |")
open("VERIFY.md", "w").write("\n".join(out) + "\n")
print(len(rows), "rows")
